### ISSUE TITLE
compilation fail (linux)

### ISSUE THREAD

**Issue by Olm-e** [sat-metalab/vrpn-openvr#3]
hello,
I try to setup this lib but it fail to compile either with gcc or clang
linux mint18=ubuntu16.04LTS gcc5.4

vrpn is compiled and installed (if not cmake doesn't configure) as well as openvr
 
with gcc I have following error : 
```

 [60%] Building CXX object CMakeFiles/vrpnOpenVR.dir/VRPN-OpenVR/main.cpp.o
In file included from /usr/include/c++/5/bits/hashtable.h:35:0,
                 from /usr/include/c++/5/unordered_map:47,
                 from /media/simedis/39de4a6b-808f-4262-946f-f0a95c61e8df/openvr/vrpn-openvr/VRPN-OpenVR/vrpn_Server_OpenVR.h:3,
                 from /media/simedis/39de4a6b-808f-4262-946f-f0a95c61e8df/openvr/vrpn-openvr/VRPN-OpenVR/main.cpp:6:
/usr/include/c++/5/bits/hashtable_policy.h: In instantiation of ‘struct std::__detail::__is_noexcept_hash<vr::ETrackedControllerRole, std::hash<vr::ETrackedControllerRole> >’:
/usr/include/c++/5/type_traits:137:12:   required from ‘struct std::__and_<std::__is_fast_hash<std::hash<vr::ETrackedControllerRole> >, std::__detail::__is_noexcept_hash<vr::ETrackedControllerRole, std::hash<vr::ETrackedControllerRole> > >’
/usr/include/c++/5/type_traits:148:38:   required from ‘struct std::__not_<std::__and_<std::__is_fast_hash<std::hash<vr::ETrackedControllerRole> >, std::__detail::__is_noexcept_hash<vr::ETrackedControllerRole, std::hash<vr::ETrackedControllerRole> > > >’
/usr/include/c++/5/bits/unordered_map.h:100:66:   required from ‘class std::unordered_map<vr::ETrackedControllerRole, std::unique_ptr<vrpn_Tracker_OpenVR_Controller> >’
/media/simedis/39de4a6b-808f-4262-946f-f0a95c61e8df/openvr/vrpn-openvr/VRPN-OpenVR/vrpn_Server_OpenVR.h:52:107:   required from here
/usr/include/c++/5/bits/hashtable_policy.h:85:34: error: no match for call to ‘(const std::hash<vr::ETrackedControllerRole>) (const vr::ETrackedControllerRole&)’
  noexcept(declval<const _Hash&>()(declval<const _Key&>()))>
                                  ^
In file included from /usr/include/c++/5/bits/move.h:57:0,
                 from /usr/include/c++/5/bits/stl_pair.h:59,
                 from /usr/include/c++/5/bits/stl_algobase.h:64,
                 from /usr/include/c++/5/memory:62,
                 from /media/simedis/39de4a6b-808f-4262-946f-f0a95c61e8df/openvr/vrpn-openvr/VRPN-OpenVR/main.cpp:5:
/usr/include/c++/5/type_traits: In instantiation of ‘struct std::__not_<std::__and_<std::__is_fast_hash<std::hash<vr::ETrackedControllerRole> >, std::__detail::__is_noexcept_hash<vr::ETrackedControllerRole, std::hash<vr::ETrackedControllerRole> > > >’:
/usr/include/c++/5/bits/unordered_map.h:100:66:   required from ‘class std::unordered_map<vr::ETrackedControllerRole, std::unique_ptr<vrpn_Tracker_OpenVR_Controller> >’
/media/simedis/39de4a6b-808f-4262-946f-f0a95c61e8df/openvr/vrpn-openvr/VRPN-OpenVR/vrpn_Server_OpenVR.h:52:107:   required from here
/usr/include/c++/5/type_traits:148:38: error: ‘value’ is not a member of ‘std::__and_<std::__is_fast_hash<std::hash<vr::ETrackedControllerRole> >, std::__detail::__is_noexcept_hash<vr::ETrackedControllerRole, std::hash<vr::ETrackedControllerRole> > >’
     : public integral_constant<bool, !_Pp::value>
                                      ^
In file included from /usr/include/c++/5/unordered_map:48:0,
                 from /media/simedis/39de4a6b-808f-4262-946f-f0a95c61e8df/openvr/vrpn-openvr/VRPN-OpenVR/vrpn_Server_OpenVR.h:3,
                 from /media/simedis/39de4a6b-808f-4262-946f-f0a95c61e8df/openvr/vrpn-openvr/VRPN-OpenVR/main.cpp:6:
/usr/include/c++/5/bits/unordered_map.h: In instantiation of ‘class std::unordered_map<vr::ETrackedControllerRole, std::unique_ptr<vrpn_Tracker_OpenVR_Controller> >’:
/media/simedis/39de4a6b-808f-4262-946f-f0a95c61e8df/openvr/vrpn-openvr/VRPN-OpenVR/vrpn_Server_OpenVR.h:52:107:   required from here
/usr/include/c++/5/bits/unordered_map.h:100:66: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<vr::ETrackedControllerRole> >, std::__detail::__is_noexcept_hash<vr::ETrackedControllerRole, std::hash<vr::ETrackedControllerRole> > > >’
       typedef __umap_hashtable<_Key, _Tp, _Hash, _Pred, _Alloc>  _Hashtable;
                                                                  ^
/usr/include/c++/5/bits/unordered_map.h:107:45: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<vr::ETrackedControllerRole> >, std::__detail::__is_noexcept_hash<vr::ETrackedControllerRole, std::hash<vr::ETrackedControllerRole> > > >’
       typedef typename _Hashtable::key_type key_type;
                                             ^
/usr/include/c++/5/bits/unordered_map.h:108:47: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<vr::ETrackedControllerRole> >, std::__detail::__is_noexcept_hash<vr::ETrackedControllerRole, std::hash<vr::ETrackedControllerRole> > > >’
       typedef typename _Hashtable::value_type value_type;
                                               ^
/usr/include/c++/5/bits/unordered_map.h:109:48: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<vr::ETrackedControllerRole> >, std::__detail::__is_noexcept_hash<vr::ETrackedControllerRole, std::hash<vr::ETrackedControllerRole> > > >’
       typedef typename _Hashtable::mapped_type mapped_type;
                                                ^
/usr/include/c++/5/bits/unordered_map.h:110:43: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<vr::ETrackedControllerRole> >, std::__detail::__is_noexcept_hash<vr::ETrackedControllerRole, std::hash<vr::ETrackedControllerRole> > > >’
       typedef typename _Hashtable::hasher hasher;
                                           ^
/usr/include/c++/5/bits/unordered_map.h:111:46: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<vr::ETrackedControllerRole> >, std::__detail::__is_noexcept_hash<vr::ETrackedControllerRole, std::hash<vr::ETrackedControllerRole> > > >’
       typedef typename _Hashtable::key_equal key_equal;
                                              ^
/usr/include/c++/5/bits/unordered_map.h:112:51: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<vr::ETrackedControllerRole> >, std::__detail::__is_noexcept_hash<vr::ETrackedControllerRole, std::hash<vr::ETrackedControllerRole> > > >’
       typedef typename _Hashtable::allocator_type allocator_type;
                                                   ^
/usr/include/c++/5/bits/unordered_map.h:117:45: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<vr::ETrackedControllerRole> >, std::__detail::__is_noexcept_hash<vr::ETrackedControllerRole, std::hash<vr::ETrackedControllerRole> > > >’
       typedef typename _Hashtable::pointer  pointer;
                                             ^
/usr/include/c++/5/bits/unordered_map.h:118:50: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<vr::ETrackedControllerRole> >, std::__detail::__is_noexcept_hash<vr::ETrackedControllerRole, std::hash<vr::ETrackedControllerRole> > > >’
       typedef typename _Hashtable::const_pointer const_pointer;
                                                  ^
/usr/include/c++/5/bits/unordered_map.h:119:47: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<vr::ETrackedControllerRole> >, std::__detail::__is_noexcept_hash<vr::ETrackedControllerRole, std::hash<vr::ETrackedControllerRole> > > >’
       typedef typename _Hashtable::reference  reference;
                                               ^
/usr/include/c++/5/bits/unordered_map.h:120:52: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<vr::ETrackedControllerRole> >, std::__detail::__is_noexcept_hash<vr::ETrackedControllerRole, std::hash<vr::ETrackedControllerRole> > > >’
       typedef typename _Hashtable::const_reference const_reference;
                                                    ^
/usr/include/c++/5/bits/unordered_map.h:121:46: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<vr::ETrackedControllerRole> >, std::__detail::__is_noexcept_hash<vr::ETrackedControllerRole, std::hash<vr::ETrackedControllerRole> > > >’
       typedef typename _Hashtable::iterator  iterator;
                                              ^
/usr/include/c++/5/bits/unordered_map.h:122:51: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<vr::ETrackedControllerRole> >, std::__detail::__is_noexcept_hash<vr::ETrackedControllerRole, std::hash<vr::ETrackedControllerRole> > > >’
       typedef typename _Hashtable::const_iterator const_iterator;
                                                   ^
/usr/include/c++/5/bits/unordered_map.h:123:51: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<vr::ETrackedControllerRole> >, std::__detail::__is_noexcept_hash<vr::ETrackedControllerRole, std::hash<vr::ETrackedControllerRole> > > >’
       typedef typename _Hashtable::local_iterator local_iterator;
                                                   ^
/usr/include/c++/5/bits/unordered_map.h:124:57: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<vr::ETrackedControllerRole> >, std::__detail::__is_noexcept_hash<vr::ETrackedControllerRole, std::hash<vr::ETrackedControllerRole> > > >’
       typedef typename _Hashtable::const_local_iterator const_local_iterator;
                                                         ^
/usr/include/c++/5/bits/unordered_map.h:125:47: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<vr::ETrackedControllerRole> >, std::__detail::__is_noexcept_hash<vr::ETrackedControllerRole, std::hash<vr::ETrackedControllerRole> > > >’
       typedef typename _Hashtable::size_type  size_type;
                                               ^
/usr/include/c++/5/bits/unordered_map.h:126:52: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<vr::ETrackedControllerRole> >, std::__detail::__is_noexcept_hash<vr::ETrackedControllerRole, std::hash<vr::ETrackedControllerRole> > > >’
       typedef typename _Hashtable::difference_type difference_type;
                                                    ^
/usr/include/c++/5/bits/unordered_map.h:280:7: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<vr::ETrackedControllerRole> >, std::__detail::__is_noexcept_hash<vr::ETrackedControllerRole, std::hash<vr::ETrackedControllerRole> > > >’
       operator=(initializer_list<value_type> __l)
       ^
/usr/include/c++/5/bits/unordered_map.h:379:2: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<vr::ETrackedControllerRole> >, std::__detail::__is_noexcept_hash<vr::ETrackedControllerRole, std::hash<vr::ETrackedControllerRole> > > >’
  emplace(_Args&&... __args)
  ^
/usr/include/c++/5/bits/unordered_map.h:432:7: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<vr::ETrackedControllerRole> >, std::__detail::__is_noexcept_hash<vr::ETrackedControllerRole, std::hash<vr::ETrackedControllerRole> > > >’
       insert(const value_type& __x)
       ^
/usr/include/c++/5/bits/unordered_map.h:439:2: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<vr::ETrackedControllerRole> >, std::__detail::__is_noexcept_hash<vr::ETrackedControllerRole, std::hash<vr::ETrackedControllerRole> > > >’
  insert(_Pair&& __x)
  ^
/usr/include/c++/5/bits/unordered_map.h:499:7: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<vr::ETrackedControllerRole> >, std::__detail::__is_noexcept_hash<vr::ETrackedControllerRole, std::hash<vr::ETrackedControllerRole> > > >’
       insert(initializer_list<value_type> __l)
       ^
/usr/include/c++/5/bits/unordered_map.h:645:7: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<vr::ETrackedControllerRole> >, std::__detail::__is_noexcept_hash<vr::ETrackedControllerRole, std::hash<vr::ETrackedControllerRole> > > >’
       equal_range(const key_type& __x)
       ^
/usr/include/c++/5/bits/unordered_map.h:649:7: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<vr::ETrackedControllerRole> >, std::__detail::__is_noexcept_hash<vr::ETrackedControllerRole, std::hash<vr::ETrackedControllerRole> > > >’
       equal_range(const key_type& __x) const
       ^
CMakeFiles/vrpnOpenVR.dir/build.make:62: recipe for target 'CMakeFiles/vrpnOpenVR.dir/VRPN-OpenVR/main.cpp.o' failed
make[2]: *** [CMakeFiles/vrpnOpenVR.dir/VRPN-OpenVR/main.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/vrpnOpenVR.dir/all' failed
make[1]: *** [CMakeFiles/vrpnOpenVR.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by ubald** [comment]
@paperManu ping!

**Comment by paperManu** [comment]
Hi Olm-e

Indeed, it does not compile on Mint 18.3, we usually build it on Ubuntu 17.10 these days which ships with GCC 7.2. It seems that GCC 5.4 does not know how to create a hash from an enum.

I pushed a quick fix in the `fix/gcc54_hash_from_enum`, which should work. I do not have the hardware at hand to test it, so please tell me whether it solves the issue or not.

(thanks for the ping @ubald ;)

**Comment by Olm-e** [comment]
great ! looks like it compile now, thanks for the quick response :)

**Comment by Olm-e** [comment]
so this issue can be closed, it works, and I used it to do a bridge for the blender game engine ;)
(working embryo : )
https://framagit.org/Olm-e/bge-vrpn-openvr
